### ISSUE TITLE
Issue on how to set a Value

### ISSUE THREAD

**Issue by jeanchristiantoure** [barberboy/chat-anarchy#3]
Good afternoon sir,
I am not sure on how to set the value of tempInCelsius to the Celsius equivalent, rounded to the nearest whole number.
**Create a new variable tempInCelsius, and set its value equal to the Celsius equivalent, rounded to the nearest whole number. The Celsius equivalent should be calculated by calling the toCelsius function property on Temperature, passing it tempToday. Round the result by using the Math.round() function.**

**Comment by barberboy** [comment]
Hi, Christian!

This isn't the right place to ask questions—I almost didn't see it. 

Please join the Gitter Chat Room here: https://gitter.im/unioncollege-webtech to be able to see class announcements.

The place to ask questions about the Temperature Converter assignment is here: https://gitter.im/unioncollege-webtech/temperature-converter

**Comment by barberboy** [comment]
I made a walk-through video of the Temperature Converter exercise that's available here: https://www.youtube.com/watch?v=7vtgwVFZEAw. I think that might answer your question.
